name: build, push, and release to main repo

# only run on changes to main
on:
  push:
    branches: [ main ]

concurrency: # prevent concurrent deploys doing strange things
  group: build-and-push
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Install deps and build
      run: |
        npm i
        grunt deploy
    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: 'deploy'
        destination-github-username: 'claire-west'
        destination-repository-name: 'svstudio-scripts'
        user-email: bokthaku@gmail.com
        target-branch: main

    - id: changed-files
      uses: tj-actions/changed-files@v35
    - id: changed-files-specific
      uses: tj-actions/changed-files@v35
      with:
        since_last_remote_commit: true
        separator: ","
        files: |
          automation/**
          hotkey-scripts/**
          utility/**
    - if: steps.changed-files-specific.outputs.any_changed == 'true'
      run: |
        echo -e "Files changed in this release:\n\n* ${{ steps.changed-files-specific.outputs.all_changed_files }}" > ${{ github.workspace }}-CHANGELOG.txt
        sed -i 's/,/\n* /g' ${{ github.workspace }}-CHANGELOG.txt

    - name: Delete latest release
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.RELEASE_PAT }}
        script: |
          await github.rest.git.deleteRef({ owner: 'claire-west', repo: 'svstudio-scripts', ref: 'tags/latest' })
    - name: Release archive
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        name: Latest Release
        tag_name: latest
        repository: claire-west/svstudio-scripts
        token: ${{ secrets.RELEASE_PAT }}
        body_path: ${{ github.workspace }}-CHANGELOG.txt
        files: |
          cw-svstudio-scripts.zip